### ISSUE TITLE
Some questions about model framework

### ISSUE THREAD

**Issue by zhou-1314** [Hao-Zou-lab/Deep-scSTAR#1]
Vb means matrix of Batch effect and Vs means reconstructed matrix, right? What do the Vhat, and Vn represent? Looking forward to your reply, thank you.

**Comment by Hao-Zou-lab** [comment]
Vhat means the reconstructed and denoised signal and Vn is noise. Please refer to the scSTAR paper.



                       
原始邮件
                       
                     

发件人："Weige Zhou"< ***@***.*** &gt;;

发件时间：2024/4/11 23:29

收件人："Hao-Zou-lab/Deep-scSTAR"< ***@***.*** &gt;;

抄送人："Subscribed"< ***@***.*** &gt;;

主题：[Hao-Zou-lab/Deep-scSTAR] Some questions about model framework (Issue#1)




 
Vb means matrix of Batch effect and Vs means reconstructed matrix, right? What do the Vhat, and Vn represent? Looking forward to your reply, thank you.

**Comment by zhou-1314** [comment]
Got it, thank you.
